//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugraSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogYorumlar
    {
        public int Id { get; set; }
        public int BlogId { get; set; }
        public string AdSoyad { get; set; }
        public string Mail { get; set; }
        public string Yorum { get; set; }
        public string Durum { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string OkunduMu { get; set; }
        public string YanitVerildiMi { get; set; }
    }
}
