//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugraSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogYorumYeni
    {
        public int BlogID { get; set; }
        public string BlogBaslik { get; set; }
        public string YorumAdSoyad { get; set; }
        public string YorumMail { get; set; }
        public string YorumIcerik { get; set; }
        public string YorumDurum { get; set; }
        public Nullable<System.DateTime> YorumTarih { get; set; }
        public string YorumOkunduMu { get; set; }
        public int YorumID { get; set; }
        public int YanitID { get; set; }
        public string YanitIcerik { get; set; }
        public Nullable<System.DateTime> YanitTarih { get; set; }
    }
}
