//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugraSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bugrasiteEntities : DbContext
    {
        public bugrasiteEntities()
            : base("name=bugrasiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Bloglar> Bloglars { get; set; }
        public virtual DbSet<BlogYorumlar> BlogYorumlars { get; set; }
        public virtual DbSet<Hakkimda> Hakkimdas { get; set; }
        public virtual DbSet<Iletisim> Iletisims { get; set; }
        public virtual DbSet<Kategoriler> Kategorilers { get; set; }
        public virtual DbSet<Mesajlar> Mesajlars { get; set; }
        public virtual DbSet<Projeler> Projelers { get; set; }
        public virtual DbSet<Referanslar> Referanslars { get; set; }
        public virtual DbSet<Tur> Turs { get; set; }
        public virtual DbSet<VisitorLog> VisitorLogs { get; set; }
        public virtual DbSet<Yetenekler> Yeteneklers { get; set; }
        public virtual DbSet<Yorumlar> Yorumlars { get; set; }
        public virtual DbSet<BloglarView> BloglarViews { get; set; }
        public virtual DbSet<BlogYorumlarView> BlogYorumlarViews { get; set; }
        public virtual DbSet<BlogYorumYanitView> BlogYorumYanitViews { get; set; }
        public virtual DbSet<ProjelerView> ProjelerViews { get; set; }
        public virtual DbSet<BlogYorumYeni> BlogYorumYenis { get; set; }
        public virtual DbSet<BlogYorumYanit> BlogYorumYanits { get; set; }
    }
}
