//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugraSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorLog
    {
        public int ID { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
