//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugraSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yetenekler
    {
        public byte Id { get; set; }
        public string Adi { get; set; }
        public Nullable<byte> Yuzdesi { get; set; }
        public string Renk { get; set; }
    }
}
