//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lotusyemek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuView
    {
        public int Menü_No { get; set; }
        public string Yemek_1_Ad { get; set; }
        public string Yemek_1_Resim { get; set; }
        public string Yemek_1_Açıklama { get; set; }
        public string Yemek_2_Ad { get; set; }
        public string Yemek_2_Resim { get; set; }
        public string Yemek_2_Açıklama { get; set; }
        public string Yemek_4_Ad { get; set; }
        public string Yemek_4_Resim { get; set; }
        public string Yemek_4_Açıklama { get; set; }
        public string Yemek_3_Ad { get; set; }
        public string Yemek_3_Resim { get; set; }
        public string Yemek_3_Açıklama { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    }
}
