//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lotusyemek.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lotusEntities : DbContext
    {
        public lotusEntities()
            : base("name=lotusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblMenu> TblMenus { get; set; }
        public virtual DbSet<TblMesaj> TblMesajs { get; set; }
        public virtual DbSet<TblYemek1> TblYemek1 { get; set; }
        public virtual DbSet<TblYemek2> TblYemek2 { get; set; }
        public virtual DbSet<TblYemek3> TblYemek3 { get; set; }
        public virtual DbSet<TblYemek4> TblYemek4 { get; set; }
        public virtual DbSet<MenuView> MenuViews { get; set; }
        public virtual DbSet<TblAdmin> TblAdmins { get; set; }
    }
}
