//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lotusyemek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAdmin
    {
        public short ID { get; set; }
        public string kadi { get; set; }
        public string sifre { get; set; }
    }
}
