//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lotusyemek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMenu
    {
        public int ID { get; set; }
        public Nullable<short> yemek1 { get; set; }
        public Nullable<short> yemek2 { get; set; }
        public Nullable<short> yemek3 { get; set; }
        public Nullable<short> yemek4 { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    }
}
