//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lotusyemek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMesaj
    {
        public int ID { get; set; }
        public string adsoyad { get; set; }
        public string mail { get; set; }
        public string tel { get; set; }
        public string aciklama { get; set; }
        public string durum { get; set; }
    }
}
